server:
  port: ${PORT:3333}

spring:
  application:
    name: customer-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  ConnectionTimeout: ${RNCT:2000}
  ReadTimeout: ${RNRT:9000}

logging:
  level:
    com.netflix.ribbon: DEBUG
    com.netflix.hystrix: DEBUG

#Enable for Scenarios 1,2,3
#feign:
#  hystrix:
#    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
#          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: ${HXT:10000}
